name: Deploy

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest # Bổ sung hệ điều hành chạy workflow
    steps: # Bổ sung từ khóa để chứa danh sách các bước
      - name: Extract and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            cd registration
            git fetch origin
            git checkout production
            git pull
            docker compose down
            docker compose up -d --build
